### ISSUE TITLE
Wallet login

### ISSUE THREAD

**Issue by lihaizeZZ** [deusexratio/Ultimate_Hemi_Testnet_Tool#1]
Dude, automatic login to fill in the invitation code can not get JWT you can solve?

**Comment by fastfoodenjoyer** [comment]
lol, didn’t even try to implement auto login, maybe will look into it next week
For now only can say that big fix for issues with queue and hemi functions coming in a couple of days (creating safe doesn’t work in current 1.0.1 version)
